nome = (input('Favor, digite seu nome para fazermos uma análise: '))
ma = nome.upper()
mi = nome.lower()
separar = len(nome) - nome.count(nome)
print('Seu nome em maiusculo fica {}'.format(ma))
print('Seu nome em minisculo fica {}'.format(mi))
print('A quantidade de letras é {}'.format(separar))